# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-21 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activelife', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVLTiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('genre', models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme'), ('Non renseign\xe9', 'Non renseign\xe9')], default='', max_length=100)),
                ('anniversaire', models.DateTimeField(default='', verbose_name='Date de naissance')),
            ],
        ),
        migrations.RemoveField(
            model_name='activlcandidat',
            name='anniversaire',
        ),
        migrations.RemoveField(
            model_name='activlcandidat',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='activlcandidat',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='activlcandidat',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='activlcandidat',
            name='valCritereGeo',
        ),
        migrations.RemoveField(
            model_name='activlcandidat',
            name='valCritereIdees',
        ),
        migrations.RemoveField(
            model_name='activlcandidat',
            name='valCriterePrixM2',
        ),
        migrations.RemoveField(
            model_name='activlcandidat',
            name='valCritereVillePop',
        ),
        migrations.RemoveField(
            model_name='activlrecruteur',
            name='valCritereGeo',
        ),
        migrations.RemoveField(
            model_name='activlrecruteur',
            name='valCritereIdees',
        ),
        migrations.RemoveField(
            model_name='activlrecruteur',
            name='valCriterePrixM2',
        ),
        migrations.RemoveField(
            model_name='activlrecruteur',
            name='valCritereVillePop',
        ),
        migrations.AlterField(
            model_name='activlcandidat',
            name='identPE',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='activlcandidat',
            name='tiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers'),
        ),
        migrations.AddField(
            model_name='activlcritgeo',
            name='tiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers'),
        ),
        migrations.AddField(
            model_name='activlcritidees',
            name='tiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers'),
        ),
        migrations.AddField(
            model_name='activlcritprixm2',
            name='tiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers'),
        ),
        migrations.AddField(
            model_name='activlcritvillepop',
            name='tiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers'),
        ),
    ]
