# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-21 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activelife', '0002_auto_20160322_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activlcritvillepop',
            name='valeur',
        ),
        migrations.AddField(
            model_name='activlcritvillepop',
            name='valeurMax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activlcritvillepop',
            name='valeurMin',
            field=models.FloatField(default=0),
        ),
    ]
