# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activelife', '0003_auto_20160322_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='activltiers',
            name='typeTiers',
            field=models.CharField(choices=[('Candidat', 'Candidat'), ('Recruteur', 'Recruteur')], editable=False, max_length=100, null=True),
        ),
    ]
