# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-24 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activelife', '0004_activltiers_typetiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activlcritprixm2',
            name='valeur',
        ),
        migrations.AddField(
            model_name='activlcritprixm2',
            name='valeurMax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activlcritprixm2',
            name='valeurMin',
            field=models.FloatField(default=0),
        ),
    ]
