# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-29 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activelife', '0005_auto_20160324_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='romedp',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ROMEGD'),
        ),
    ]
