# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-30 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activelife', '0008_auto_20160330_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVLCritMetierROMEAp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib', models.CharField(default='M\xe9tier ROME : appellation OGR', editable=False, max_length=100)),
                ('valeur', models.CharField(choices=[('Mer', 'Mer'), ('Montagne', 'Montagne'), ('Campagne', 'Campagne')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVLCritMetierROMEDP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib', models.CharField(default='M\xe9tier ROME : Domaine professionnel', editable=False, max_length=100)),
                ('valeur', models.CharField(choices=[('Mer', 'Mer'), ('Montagne', 'Montagne'), ('Campagne', 'Campagne')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVLCritMetierROMEFi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib', models.CharField(default='M\xe9tier ROME : Fiche ROME', editable=False, max_length=100)),
                ('valeur', models.CharField(choices=[('Mer', 'Mer'), ('Montagne', 'Montagne'), ('Campagne', 'Campagne')], max_length=100)),
                ('tiers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLCritMetierROMEDP')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVLCritMetierROMEGD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib', models.CharField(default='M\xe9tier ROME : Grand domaine', editable=False, max_length=100)),
                ('valeur', models.CharField(choices=[('Mer', 'Mer'), ('Montagne', 'Montagne'), ('Campagne', 'Campagne')], max_length=100)),
                ('tiers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers')),
            ],
        ),
        migrations.AddField(
            model_name='activlcritmetierromedp',
            name='tiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLCritMetierROMEGD'),
        ),
        migrations.AddField(
            model_name='activlcritmetierromeap',
            name='tiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLCritMetierROMEFi'),
        ),
    ]
