# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-30 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activelife', '0010_auto_20160331_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activlcritmetierromegd',
            old_name='parent',
            new_name='tiers',
        ),
        migrations.AddField(
            model_name='activlcritmetierromeap',
            name='tiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers'),
        ),
        migrations.AddField(
            model_name='activlcritmetierromedp',
            name='tiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers'),
        ),
        migrations.AddField(
            model_name='activlcritmetierromefi',
            name='tiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers'),
        ),
    ]
