# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-07 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activelife', '0012_auto_20160406_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activltiers',
            name='anniversaire',
            field=models.DateTimeField(default='', null=True, verbose_name='Date de naissance'),
        ),
    ]
