# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-20 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activelife', '0014_auto_20160418_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVLCritExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField()),
                ('tiers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVLCritRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=100, null=True)),
                ('tiers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVLCritSalaireAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=100)),
                ('tiers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVLCritSalaireJour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=100)),
                ('tiers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVLCritSalaireMois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=100)),
                ('tiers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVLCritVille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=100, null=True)),
                ('tiers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activelife.ACTIVLTiers')),
            ],
        ),
        migrations.RemoveField(
            model_name='activlcritmetierromeap',
            name='lib',
        ),
        migrations.RemoveField(
            model_name='activlcritmetierromedp',
            name='lib',
        ),
        migrations.RemoveField(
            model_name='activlcritmetierromefi',
            name='lib',
        ),
        migrations.RemoveField(
            model_name='activlcritmetierromegd',
            name='lib',
        ),
    ]
