# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-20 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activelife', '0015_auto_20160421_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activlcritexperience',
            name='valeur',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activlcritsalairean',
            name='valeur',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='activlcritsalairejour',
            name='valeur',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='activlcritsalairemois',
            name='valeur',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
